[package]
name = "wasmer/wasmer-io"
version = "0.6.1"
description = "The wasmer.io website"
readme = "README.md"

[dependencies]
"wasmer/static-web-server" = "1"

[fs]
"public" = "public"
"cfg" = "cfg"
