on:
  push:
    branches:
      - "master"

env:
  RUST_BACKTRACE: full

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Publish to wasmer.io
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions/checkout@v3
        with:
          toolchain: stable

      - name: Install the Deploy CLI
        uses: actions-rs/install@v0.1
        with:
          crate: wasmer-deploy-cli
          version: 0.1.4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build and publish
        run: ./deploy.sh
        env:
          WASMER_TOKEN: ${{ secrets.WAPM_PROD_TOKEN }}
