on:
  push:
    branches:
      - "master"

env:
  RUST_BACKTRACE: full

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Publish to wasmer.io
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions/checkout@v3
        with:
          toolchain: stable

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Install the Deploy CLI
        run: command -v wasmer-deploy &>/dev/null || cargo install --verbose --debug --locked wasmer-deploy-cli

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      # This is a hack for https://github.com/wasmerio/wasmer/issues/3744
      # Ideally, we would just have `"public" = "out"` under the `[fs]` table
      # in `wasmer.toml`
      - name: wasmerio/wasmer#3744 Hack
        run: |
          mv public public.bak
          mv out public

      - name: Publish
        run: wasmer-deploy publish --publish-package --token=${{ secrets.WAPM_DEV_TOKEN }} --non-interactive
