on:
  push:
    branches:
      - "master"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Publish to wasmer.io
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Rust
        uses: actions/checkout@v3
        with:
          toolchain: stable
      - name: Install the Deploy CLI
        uses: actions-rs/install@v0.1
        with:
          crate: wasmer-deploy-cli
          version: latest
      - name: Build the website
        run: npm install && npm run build
      # This is a hack for https://github.com/wasmerio/wasmer/issues/3744
      # Ideally, we would just have `"public" = "out"` under the `[fs]` table
      # in `wasmer.toml`
      - name: wasmerio/wasmer#3744 Hack
        run: |
          mv public public.bak
          mv out public
      - name: Publish
        run: wasmer-deploy publish --publish-package --token=${{ secrets.WAPM_DEV_TOKEN }} --registry=https://wapm.dev/ --non-interactive
